
### Post Comminity(Success)

POST http://localhost:8080/communities
Authorization: Bearer test1
Content-Type: application/json

{
    "cateId" : "5",
    "content" : "내용입니다",
    "title" : "제목111"
}

### Get Comminity(Success)

GET http://localhost:8080/communities?title=제목
Authorization: Bearer test
Content-Type: application/json

### Get Comminity(Success)

GET http://localhost:8080/communities
Authorization: Bearer test
Content-Type: application/json

### Delete Comminity(Success)

DELETE http://localhost:8080/communities/11
Authorization: Bearer test
Content-Type: application/json



